import type { Project, BrainPattern, GuardianAlert, AgentType, AgentTask, AgentFullConfig } from "./types";

const now = Date.now();
const minsAgo = (m: number) => new Date(now - m * 60000);
const hoursAgo = (h: number) => new Date(now - h * 3600000);
const daysAgo = (d: number) => new Date(now - d * 86400000);

export const DEMO_PROJECTS: Project[] = [
  {
    id: "p1",
    name: "NuestraOferta",
    slug: "nuestraoferta",
    description: "Marketplace de ofertas locales para LATAM",
    status: "healthy",
    url: "https://nuestraoferta.com",
    repoUrl: "https://github.com/pedro2g/nuestraoferta",
    stack: ["Next.js", "Supabase", "Polar"],
    designSystem: "gradient-mesh",
    uptimeSeconds: 1847320,
    uptimePct: 99.97,
    revenueCents: 487500,
    revenueGrowthPct: 23.4,
    activeUsers: 1247,
    conversionPct: 4.1,
    deployedAt: daysAgo(21),
    lastCommit: "fix: optimize checkout flow",
    lastCommitAt: hoursAgo(3),
    guardianEnabled: true,
    errorsLast24h: 2,
    p95LatencyMs: 187,
  },
  {
    id: "p2",
    name: "RidePG",
    slug: "ridepg",
    description: "App de movilidad urbana on-demand",
    status: "healthy",
    url: "https://ridepg.app",
    repoUrl: "https://github.com/pedro2g/ridepg",
    stack: ["Next.js", "Supabase", "Resend"],
    designSystem: "neobrutalism",
    uptimeSeconds: 892440,
    uptimePct: 99.91,
    revenueCents: 218000,
    revenueGrowthPct: 41.2,
    activeUsers: 843,
    conversionPct: 3.7,
    deployedAt: daysAgo(10),
    lastCommit: "feat: add driver tracking map",
    lastCommitAt: hoursAgo(7),
    guardianEnabled: true,
    errorsLast24h: 0,
    p95LatencyMs: 142,
  },
  {
    id: "p3",
    name: "FractalOS",
    slug: "fractals-os",
    description: "Sistema operativo de agentes para empresas",
    status: "deploying",
    url: "https://fractal-os.vercel.app",
    repoUrl: "https://github.com/pedro2g/fractals-os",
    stack: ["Next.js", "Supabase", "OpenRouter"],
    designSystem: "liquid-glass",
    uptimeSeconds: 432100,
    uptimePct: 99.42,
    revenueCents: 95000,
    revenueGrowthPct: 87.5,
    activeUsers: 312,
    conversionPct: 5.2,
    deployedAt: daysAgo(5),
    lastCommit: "feat: multi-agent orchestration v2",
    lastCommitAt: minsAgo(12),
    guardianEnabled: true,
    errorsLast24h: 8,
    p95LatencyMs: 298,
  },
  {
    id: "p4",
    name: "Dental Mgmt",
    slug: "dental-mngmt",
    description: "Sistema de gestion para clinicas dentales",
    status: "degraded",
    url: "https://dental-mngmt.vercel.app",
    repoUrl: "https://github.com/pedro2g/dental-mngmt",
    stack: ["Next.js", "Supabase"],
    designSystem: "neumorphism",
    uptimeSeconds: 2240100,
    uptimePct: 97.3,
    revenueCents: 134000,
    revenueGrowthPct: 5.1,
    activeUsers: 89,
    conversionPct: 2.1,
    deployedAt: daysAgo(26),
    lastCommit: "fix: patient record export",
    lastCommitAt: hoursAgo(18),
    guardianEnabled: false,
    errorsLast24h: 47,
    p95LatencyMs: 1240,
  },
  {
    id: "p5",
    name: "BusinessOS",
    slug: "business-os",
    description: "Template de OS para negocios digitales",
    status: "healthy",
    url: "https://business-os.vercel.app",
    repoUrl: "https://github.com/pedro2g/business-os-template",
    stack: ["Next.js", "Supabase", "Polar", "Resend"],
    designSystem: "bento-grid",
    uptimeSeconds: 3102400,
    uptimePct: 99.99,
    revenueCents: 312000,
    revenueGrowthPct: 12.8,
    activeUsers: 567,
    conversionPct: 3.9,
    deployedAt: daysAgo(36),
    lastCommit: "docs: update onboarding guide",
    lastCommitAt: daysAgo(1),
    guardianEnabled: true,
    errorsLast24h: 1,
    p95LatencyMs: 95,
  },
  {
    id: "p6",
    name: "Pipe0.1",
    slug: "pipe01",
    description: "Automatizacion de pipelines de ventas con IA",
    status: "healthy",
    url: "https://pipe01.vercel.app",
    repoUrl: "https://github.com/pedro2g/pipe0.1",
    stack: ["Next.js", "Supabase", "OpenRouter"],
    designSystem: "gradient-mesh",
    uptimeSeconds: 748800,
    uptimePct: 99.88,
    revenueCents: 76500,
    revenueGrowthPct: 156.3,
    activeUsers: 198,
    conversionPct: 6.8,
    deployedAt: daysAgo(9),
    lastCommit: "feat: AI lead scoring",
    lastCommitAt: hoursAgo(5),
    guardianEnabled: true,
    errorsLast24h: 3,
    p95LatencyMs: 224,
  },
  {
    id: "p7",
    name: "Meridian Real Estate",
    slug: "meridian-realstate",
    description: "Plataforma proptech para agentes inmobiliarios",
    status: "down",
    url: "https://meridian-re.vercel.app",
    repoUrl: "https://github.com/pedro2g/meridian-realstate",
    stack: ["Next.js", "Supabase"],
    designSystem: "neumorphism",
    uptimeSeconds: 0,
    uptimePct: 81.2,
    revenueCents: 0,
    revenueGrowthPct: -100,
    activeUsers: 0,
    conversionPct: 0,
    deployedAt: daysAgo(45),
    lastCommit: "Merge pull request #34",
    lastCommitAt: hoursAgo(2),
    guardianEnabled: false,
    errorsLast24h: 412,
    p95LatencyMs: 9999,
  },
  {
    id: "p8",
    name: "Mission Control",
    slug: "mission-control",
    description: "El cockpit de la SaaS Factory — construido por la fabrica",
    status: "healthy",
    url: "https://mission-control-sf.vercel.app",
    repoUrl: "https://github.com/pedro2g/mission-control",
    stack: ["Next.js", "Supabase", "Zustand"],
    designSystem: "dark-os",
    uptimeSeconds: 7200,
    uptimePct: 100,
    revenueCents: 0,
    revenueGrowthPct: 0,
    activeUsers: 1,
    conversionPct: 100,
    deployedAt: hoursAgo(2),
    lastCommit: "feat: initial mission control build",
    lastCommitAt: hoursAgo(2),
    guardianEnabled: true,
    errorsLast24h: 0,
    p95LatencyMs: 67,
  },
];

export const DEMO_PATTERNS: BrainPattern[] = [
  {
    id: "bp1",
    title: "gradient-mesh convierte 2x vs neumorphism",
    description: "En 4 proyectos comparados, el design system gradient-mesh supera consistentemente al neumorphism en conversiones de signup.",
    category: "design",
    confidence: "proven",
    confidencePct: 91,
    evidence: "NuestraOferta 4.1% vs Dental 2.1% | BusinessOS 3.9% vs Meridian 0% | n=4",
    projectCount: 4,
    avgConversionPct: 4.0,
    revenueImpact: "+$2,400/mes promedio",
    tags: ["design-system", "conversion", "signup"],
    discoveredAt: daysAgo(14),
  },
  {
    id: "bp2",
    title: "Polar + webhooks: setup en <2h sin friccion",
    description: "Integrar Polar como MoR toma menos de 2 horas con el skill add-payments. Sin disputas de pago en 6 proyectos.",
    category: "stack",
    confidence: "proven",
    confidencePct: 97,
    evidence: "6 proyectos, 0 disputas, avg setup 1h 47m",
    projectCount: 6,
    avgConversionPct: null,
    revenueImpact: "0 chargebacks",
    tags: ["payments", "polar", "MoR"],
    discoveredAt: daysAgo(30),
  },
  {
    id: "bp3",
    title: "OpenRouter routing reduce costo IA 67%",
    description: "Usar Haiku para clasificacion y Sonnet solo para generacion reduce el costo por usuario de $0.08 a $0.026.",
    category: "stack",
    confidence: "proven",
    confidencePct: 88,
    evidence: "FractalOS: $0.08 → $0.026/user | Pipe0.1: $0.11 → $0.033/user",
    projectCount: 2,
    avgConversionPct: null,
    revenueImpact: "-67% costo IA",
    tags: ["AI", "cost", "openrouter", "routing"],
    discoveredAt: daysAgo(7),
  },
  {
    id: "bp4",
    title: "Onboarding en <3 pasos dobla activacion",
    description: "Reducir el onboarding a 3 pasos maximos con valor visible en el paso 1 duplica la tasa de activacion.",
    category: "feature",
    confidence: "proven",
    confidencePct: 84,
    evidence: "RidePG: 31% → 67% activacion | NuestraOferta: 28% → 54%",
    projectCount: 3,
    avgConversionPct: 60.5,
    revenueImpact: "+$1,800/mes promedio",
    tags: ["onboarding", "activation", "ux"],
    discoveredAt: daysAgo(18),
  },
  {
    id: "bp5",
    title: "SEO programatico: 400 paginas en 1 deploy",
    description: "Generar paginas de ciudad+categoria con el skill acquisition produce trafico organico sostenible sin ads.",
    category: "acquisition",
    confidence: "likely",
    confidencePct: 72,
    evidence: "NuestraOferta: 400 pags → 2,300 visitas organicas/mes en 45 dias",
    projectCount: 1,
    avgConversionPct: null,
    revenueImpact: "$0 CAC desde organico",
    tags: ["SEO", "programmatic", "acquisition"],
    discoveredAt: daysAgo(10),
  },
  {
    id: "bp6",
    title: "Freemium 14-day trial convierte mejor que pago directo",
    description: "En SaaS B2B LATAM, trial de 14 dias sin tarjeta supera al pago directo en conversion de primeras 4 semanas.",
    category: "pricing",
    confidence: "likely",
    confidencePct: 76,
    evidence: "BusinessOS: 3.9% pago directo | Pipe0.1: 6.8% con trial 14d",
    projectCount: 2,
    avgConversionPct: 5.35,
    revenueImpact: "+74% conversion primera semana",
    tags: ["pricing", "freemium", "trial", "B2B"],
    discoveredAt: daysAgo(5),
  },
  {
    id: "bp7",
    title: "Guardian auto-fix en branch: 0 regresiones en main",
    description: "Activar Guardian con freno humano (PR obligatorio) elimina regresiones en main. 0 incidentes en 4 meses.",
    category: "stack",
    confidence: "proven",
    confidencePct: 95,
    evidence: "5 proyectos con Guardian: 0 regresiones | 2 sin Guardian: 3 incidentes",
    projectCount: 5,
    avgConversionPct: null,
    revenueImpact: "0 downtime incidents",
    tags: ["guardian", "devops", "reliability"],
    discoveredAt: daysAgo(45),
  },
  {
    id: "bp8",
    title: "next-intl desde dia 1 ahorra 3 dias de refactor",
    description: "Agregar i18n despues del primer deploy requiere refactor masivo. Instalarlo en el scaffold inicial no tiene costo.",
    category: "stack",
    confidence: "proven",
    confidencePct: 99,
    evidence: "Meridian: 3 dias de refactor i18n | RidePG: 0h (instalado desde inicio)",
    projectCount: 4,
    avgConversionPct: null,
    revenueImpact: "-3d de tech debt",
    tags: ["i18n", "scaffold", "next-intl"],
    discoveredAt: daysAgo(20),
  },
  {
    id: "bp9",
    title: "Email transaccional Resend: 98.7% deliverability",
    description: "Resend + React Email supera a SendGrid y Mailgun en deliverability para dominios .com.mx y .com LATAM.",
    category: "stack",
    confidence: "proven",
    confidencePct: 92,
    evidence: "4 proyectos, 98.7% avg vs 94.2% SendGrid historico",
    projectCount: 4,
    avgConversionPct: null,
    revenueImpact: "+4.5% email deliverability",
    tags: ["email", "resend", "transactional"],
    discoveredAt: daysAgo(35),
  },
  {
    id: "bp10",
    title: "bento-grid layout aumenta tiempo en pagina 40%",
    description: "El design system bento-grid en dashboards aumenta el tiempo promedio en pagina y reduce el bounce rate.",
    category: "design",
    confidence: "likely",
    confidencePct: 68,
    evidence: "BusinessOS: +40% tiempo en pagina vs baseline | n=1",
    projectCount: 1,
    avgConversionPct: 3.9,
    revenueImpact: "+40% engagement",
    tags: ["design-system", "bento-grid", "engagement"],
    discoveredAt: daysAgo(8),
  },
  {
    id: "bp11",
    title: "Compliance pre-deploy evita suspension de cuentas",
    description: "Apps LATAM sin aviso de privacidad MX (LFPDPPP) son suspendidas por app stores en promedio 3 semanas post-launch.",
    category: "feature",
    confidence: "proven",
    confidencePct: 100,
    evidence: "1 proyecto suspendido (sin compliance) vs 5 sin incidentes (con compliance)",
    projectCount: 6,
    avgConversionPct: null,
    revenueImpact: "Evitar suspension total",
    tags: ["compliance", "legal", "LATAM", "LFPDPPP"],
    discoveredAt: daysAgo(60),
  },
  {
    id: "bp12",
    title: "Supabase RLS desde migracion 0: 0 leaks de datos",
    description: "Habilitar RLS en todas las tablas desde la primera migracion previene data leaks. Retro-activarlo es costoso.",
    category: "stack",
    confidence: "proven",
    confidencePct: 100,
    evidence: "8 proyectos con RLS desde inicio: 0 leaks | 1 proyecto sin RLS inicial: data leak en semana 3",
    projectCount: 8,
    avgConversionPct: null,
    revenueImpact: "0 data breaches",
    tags: ["supabase", "RLS", "security"],
    discoveredAt: daysAgo(90),
  },
];

export const DEMO_ALERTS: GuardianAlert[] = [
  {
    id: "a1",
    projectId: "p7",
    projectName: "Meridian Real Estate",
    severity: "critical",
    type: "error_spike",
    title: "Error rate 2400% above baseline",
    detail: "TypeError: Cannot read properties of null (reading 'lat') in /api/listings — 412 errors in 2h",
    autoFixAvailable: true,
    prUrl: "https://github.com/pedro2g/meridian-realstate/pull/35",
    prStatus: "open",
    createdAt: minsAgo(127),
    resolvedAt: null,
  },
  {
    id: "a2",
    projectId: "p4",
    projectName: "Dental Mgmt",
    severity: "warning",
    type: "error_spike",
    title: "P95 latency degraded to 1240ms",
    detail: "Supabase query on patient_records table missing index on clinic_id. Full table scan detected.",
    autoFixAvailable: true,
    prUrl: "https://github.com/pedro2g/dental-mngmt/pull/18",
    prStatus: "open",
    createdAt: hoursAgo(4),
    resolvedAt: null,
  },
  {
    id: "a3",
    projectId: "p3",
    projectName: "FractalOS",
    severity: "info",
    type: "deploy",
    title: "Deploy in progress — multi-agent v2",
    detail: "Build triggered by commit feat: multi-agent orchestration v2. ETA ~4 minutes.",
    autoFixAvailable: false,
    prUrl: null,
    prStatus: null,
    createdAt: minsAgo(12),
    resolvedAt: null,
  },
  {
    id: "a4",
    projectId: "p6",
    projectName: "Pipe0.1",
    severity: "info",
    type: "revenue",
    title: "Revenue milestone: $765 MRR",
    detail: "Monthly recurring revenue crossed $765 — up 156% from last month. Guardian tracking conversion funnel.",
    autoFixAvailable: false,
    prUrl: null,
    prStatus: null,
    createdAt: hoursAgo(1),
    resolvedAt: null,
  },
  {
    id: "a5",
    projectId: "p2",
    projectName: "RidePG",
    severity: "info",
    type: "pr_opened",
    title: "Guardian auto-fix merged: null check on driver location",
    detail: "PR #22 merged automatically — added null guard on driver.location before map render. 0 errors since.",
    autoFixAvailable: false,
    prUrl: "https://github.com/pedro2g/ridepg/pull/22",
    prStatus: "merged",
    createdAt: hoursAgo(9),
    resolvedAt: hoursAgo(8),
  },
];

// ── Demo Agent Tasks ─────────────────────────────────────────────
export const DEMO_TASKS: AgentTask[] = [
  {
    id: "t1",
    agent: "guardian",
    title: "Auto-fix: TypeError en /api/listings",
    detail: "Detecté null reference en Meridian Real Estate. Analizando stack trace, generando patch con null-guard y abriendo PR para revisión humana.",
    status: "waiting_approval",
    projectId: "p7",
    projectName: "Meridian Real Estate",
    progress: 100,
    startedAt: minsAgo(8),
    approvalRequired: true,
    approvalPrompt: "Guardian quiere mergear PR #35 en meridian-realstate. El fix agrega null-check en /api/listings antes de acceder a .lat. ¿Apruebas el merge?",
    prUrl: "https://github.com/pedro2g/meridian-realstate/pull/35",
  },
  {
    id: "t2",
    agent: "guardian",
    title: "Agregar índice en patient_records.clinic_id",
    detail: "P95 latencia en 1240ms por full table scan. Generando migración de Supabase para agregar índice compuesto en clinic_id + created_at.",
    status: "running",
    projectId: "p4",
    projectName: "Dental Mgmt",
    progress: 67,
    startedAt: minsAgo(3),
    approvalRequired: true,
    approvalPrompt: "Guardian quiere aplicar migración en producción: CREATE INDEX idx_clinic_created ON patient_records(clinic_id, created_at). ¿Apruebas?",
  },
  {
    id: "t3",
    agent: "brain",
    title: "Actualizar patrón: freemium 14d vs pago directo",
    detail: "Pipe0.1 acaba de cruzar 6.8% de conversión con trial. Actualizando el patrón con nueva evidencia y recalculando confianza de LIKELY → PROVEN.",
    status: "running",
    projectId: "p6",
    projectName: "Pipe0.1",
    progress: 45,
    startedAt: minsAgo(1),
    approvalRequired: false,
  },
  {
    id: "t4",
    agent: "acquisition",
    title: "Generar 200 páginas SEO para RidePG",
    detail: "Creando páginas /transporte-[ciudad] para las 32 capitales de México con next-intl. Estimado: 800-2000 visitas orgánicas/mes en 60 días.",
    status: "queued",
    projectId: "p2",
    projectName: "RidePG",
    progress: 0,
    approvalRequired: true,
    approvalPrompt: "Acquisition quiere crear 200 páginas SEO en RidePG y hacer deploy. Tiempo estimado: 45 min. ¿Apruebas que inicie?",
  },
  {
    id: "t5",
    agent: "compliance",
    title: "Generar aviso de privacidad LFPDPPP",
    detail: "NuestraOferta recolecta datos personales sin aviso de privacidad compliant con LFPDPPP México. Generando documento y página /privacidad.",
    status: "queued",
    projectId: "p1",
    projectName: "NuestraOferta",
    progress: 0,
    approvalRequired: true,
    approvalPrompt: "Compliance quiere agregar /privacidad con aviso LFPDPPP y un banner de cookies a NuestraOferta. ¿Apruebas?",
  },
  {
    id: "t6",
    agent: "brain",
    title: "Detectar nuevo patrón: bento-grid en dashboards B2B",
    detail: "BusinessOS y FractalOS usan bento-grid y tienen +40% tiempo en página vs baseline. Creando patrón nuevo con evidencia de 2 proyectos.",
    status: "done",
    projectId: "p5",
    projectName: "BusinessOS",
    progress: 100,
    startedAt: hoursAgo(2),
    completedAt: hoursAgo(1),
    approvalRequired: false,
    result: "Patrón 'bento-grid aumenta engagement 40% en dashboards B2B' creado con confianza LIKELY (68%). Visible en Factory Brain.",
  },
  {
    id: "t7",
    agent: "guardian",
    title: "Monitor de conversión: NuestraOferta checkout",
    detail: "Vigilando el funnel de checkout después del último deploy. Alert si conversión cae >0.5% en los próximos 30 minutos.",
    status: "done",
    projectId: "p1",
    projectName: "NuestraOferta",
    progress: 100,
    startedAt: hoursAgo(3),
    completedAt: hoursAgo(2),
    approvalRequired: false,
    result: "Monitor completado. Conversión estable en 4.1% — sin regresiones detectadas en el deploy.",
  },
];

// ── Agent Full Configs ───────────────────────────────────────────
export const DEMO_AGENT_FULL_CONFIGS: AgentFullConfig[] = [
  {
    agent: "guardian",
    label: "Guardian",
    model: "claude-haiku-4-5-20251001",
    maxTokens: 1024,
    humanApprovalRequired: true,
    systemPrompt: `Eres Guardian, el agente de operaciones autónomas de Mission Control OS.
Tu misión: vigilar la salud de los proyectos en producción, detectar anomalías, y proponer fixes con evidencia.

REGLAS:
- Nunca hagas merge directo a main. Siempre branch + PR.
- Si la severidad es CRITICAL, abre PR inmediatamente y notifica.
- Si la severidad es WARNING, investiga 5 min antes de actuar.
- Incluye en el PR: root cause, fix propuesto, tests afectados.
- Espera aprobación humana antes de ejecutar cualquier migración de DB.`,
    tools: [
      { id: "read_logs",     name: "read_logs",       description: "Leer logs de Vercel y Supabase en tiempo real",        category: "read",     enabled: true  },
      { id: "read_code",     name: "read_code",        description: "Leer archivos del repositorio",                        category: "read",     enabled: true  },
      { id: "execute_sql",   name: "execute_sql",      description: "Ejecutar queries de lectura en Supabase",              category: "read",     enabled: true  },
      { id: "create_branch", name: "create_branch",    description: "Crear rama de fix en el repositorio",                  category: "write",    enabled: true  },
      { id: "write_code",    name: "write_code",       description: "Escribir archivos de código en la rama de fix",        category: "write",    enabled: true  },
      { id: "open_pr",       name: "open_pr",          description: "Abrir Pull Request con descripción del fix",           category: "write",    enabled: true  },
      { id: "run_migration", name: "run_migration",    description: "Aplicar migraciones de Supabase (requiere aprobación)", category: "write",   enabled: true,  dangerous: true },
      { id: "deploy",        name: "trigger_deploy",   description: "Triggear deploy en Vercel (requiere aprobación)",      category: "external", enabled: false, dangerous: true },
      { id: "send_alert",    name: "send_alert",       description: "Enviar alerta por email/Slack",                        category: "external", enabled: true  },
    ],
    actions: [
      { id: "auto_fix",     name: "Auto-fix en rama",          description: "Detecta error → analiza → crea branch + PR automáticamente",     requiresApproval: false, enabled: true  },
      { id: "merge_pr",     name: "Merge PR aprobado",         description: "Mergea PR tras aprobación humana",                                requiresApproval: true,  enabled: true  },
      { id: "rollback",     name: "Rollback de deploy",        description: "Revierte al deploy anterior si el actual tiene error rate >5%",   requiresApproval: true,  enabled: true  },
      { id: "scale_db",     name: "Escalar base de datos",     description: "Aumentar compute de Supabase si CPU >80% por 10 min",             requiresApproval: true,  enabled: false },
      { id: "notify_team",  name: "Notificar al equipo",       description: "Envía resumen de incidentes al Slack del proyecto",               requiresApproval: false, enabled: true  },
    ],
    skills: [
      { id: "playwright-cli", label: "playwright-cli", description: "Testing automatizado para verificar fix",     enabled: true  },
      { id: "supabase",       label: "supabase",       description: "Ejecutar migraciones y queries",              enabled: true  },
      { id: "quality-gates",  label: "quality-gates",  description: "Correr gates antes de sugerir merge",         enabled: true  },
      { id: "outcomes",       label: "outcomes",       description: "Reportar impacto del fix en métricas",        enabled: false },
    ],
    memory: {
      contextWindow: 100000,
      retainHistory: true,
      historyDepth: 20,
      crossProjectMemory: true,
      factoryBrainAccess: true,
    },
  },
  {
    agent: "brain",
    label: "Factory Brain",
    model: "claude-sonnet-4-6",
    maxTokens: 2048,
    humanApprovalRequired: false,
    systemPrompt: `Eres Factory Brain, la memoria inteligente cross-proyectos de Mission Control OS.
Tu misión: detectar patrones que funcionan (o fallan) entre proyectos y mantener el registro con evidencia.

REGLAS:
- Un patrón solo es PROVEN si tiene evidencia de ≥3 proyectos con datos reales.
- Un patrón es LIKELY con 2 proyectos o con un proyecto y métricas sólidas.
- Siempre incluye: qué se hizo, en qué proyecto, qué cambió en números.
- Nunca inventes evidencia. Si no hay datos, el patrón es EXPERIMENTAL.
- Actualiza patrones existentes antes de crear nuevos.`,
    tools: [
      { id: "read_metrics",   name: "read_metrics",    description: "Leer métricas de conversion, revenue, uptime de todos los proyectos", category: "read",  enabled: true  },
      { id: "read_patterns",  name: "read_patterns",   description: "Leer el registro actual de patrones del Brain",                       category: "read",  enabled: true  },
      { id: "write_pattern",  name: "write_pattern",   description: "Crear o actualizar un patrón en el registro",                        category: "write", enabled: true  },
      { id: "query_history",  name: "query_history",   description: "Consultar historial de decisiones técnicas cross-proyectos",         category: "read",  enabled: true  },
      { id: "call_llm",       name: "call_llm",        description: "Llamar a un modelo para análisis semántico de evidencia",            category: "ai",    enabled: true  },
    ],
    actions: [
      { id: "create_pattern",  name: "Crear patrón",          description: "Detecta evidencia nueva y crea entrada en el Brain",          requiresApproval: false, enabled: true  },
      { id: "update_pattern",  name: "Actualizar confianza",   description: "Recalcula la confianza de un patrón con nueva evidencia",     requiresApproval: false, enabled: true  },
      { id: "deprecate",       name: "Deprecar patrón",        description: "Marca un patrón como obsoleto si la evidencia lo contradice", requiresApproval: true,  enabled: true  },
      { id: "cross_project",   name: "Análisis cross-proyecto", description: "Compara comportamiento de todos los proyectos para detectar divergencias", requiresApproval: false, enabled: true },
    ],
    skills: [
      { id: "outcomes",        label: "outcomes",       description: "Ingerir resultados reales de revenue y conversión", enabled: true  },
      { id: "factory-brain",   label: "factory-brain",  description: "Skill de meta-memoria para persistencia",          enabled: true  },
      { id: "cost-optimizer",  label: "cost-optimizer", description: "Detectar patrones de costo-IA entre proyectos",    enabled: true  },
    ],
    memory: {
      contextWindow: 200000,
      retainHistory: true,
      historyDepth: 50,
      crossProjectMemory: true,
      factoryBrainAccess: true,
    },
  },
  {
    agent: "acquisition",
    label: "Acquisition",
    model: "claude-haiku-4-5-20251001",
    maxTokens: 4096,
    humanApprovalRequired: true,
    systemPrompt: `Eres el Acquisition Agent de Mission Control OS.
Tu misión: convertir proyectos deployados en proyectos con usuarios reales.

REGLAS:
- Prioriza canales con CAC $0 (SEO, contenido, redes) antes que ads pagados.
- SEO programático: genera páginas /[ciudad]/[categoria] con next-intl.
- Valida que el proyecto tiene ≥2% conversión antes de proponer ads pagados.
- Cada táctica que propones debe tener tiempo estimado y métrica de éxito.
- Documenta lo que funciona en Factory Brain.`,
    tools: [
      { id: "read_analytics",  name: "read_analytics",   description: "Leer Vercel Analytics y tabla events de Supabase",                category: "read",     enabled: true  },
      { id: "read_code",       name: "read_code",         description: "Leer el codebase del proyecto para generar páginas",             category: "read",     enabled: true  },
      { id: "generate_pages",  name: "generate_pages",    description: "Generar páginas SEO programáticas con next-intl",               category: "write",    enabled: true  },
      { id: "write_content",   name: "write_content",     description: "Generar copy para landing pages y posts",                       category: "write",    enabled: true  },
      { id: "open_pr",         name: "open_pr",           description: "Abrir PR con las páginas generadas",                            category: "write",    enabled: true  },
      { id: "google_search",   name: "google_search",     description: "Buscar keywords y volumen para SEO",                            category: "external", enabled: true  },
      { id: "submit_sitemap",  name: "submit_sitemap",    description: "Enviar sitemap a Google Search Console (requiere aprobación)",   category: "external", enabled: true,  dangerous: true },
    ],
    actions: [
      { id: "gen_seo_pages",   name: "Generar páginas SEO",     description: "Crea páginas /[ciudad]/[categoria] y abre PR",             requiresApproval: true,  enabled: true  },
      { id: "gen_content",     name: "Generar contenido",        description: "Crea posts de blog o LinkedIn para el proyecto",           requiresApproval: true,  enabled: true  },
      { id: "audit_seo",       name: "Auditar SEO actual",       description: "Revisa meta tags, sitemap, robots.txt del proyecto",       requiresApproval: false, enabled: true  },
      { id: "setup_analytics", name: "Configurar Analytics",     description: "Agrega Vercel Analytics y eventos de conversión al funnel", requiresApproval: true,  enabled: true  },
    ],
    skills: [
      { id: "acquisition",    label: "acquisition",   description: "Skill base de adquisición con templates",      enabled: true  },
      { id: "i18n",           label: "i18n",          description: "Internacionalización para páginas multi-ciudad", enabled: true  },
      { id: "compliance",     label: "compliance",    description: "Verificar que el contenido cumple regulaciones", enabled: false },
      { id: "outcomes",       label: "outcomes",      description: "Medir impacto de tráfico generado",             enabled: true  },
    ],
    memory: {
      contextWindow: 100000,
      retainHistory: true,
      historyDepth: 10,
      crossProjectMemory: true,
      factoryBrainAccess: true,
    },
  },
  {
    agent: "portfolio",
    label: "Portfolio Advisor",
    model: "claude-haiku-4-5-20251001",
    maxTokens: 1024,
    humanApprovalRequired: false,
    systemPrompt: `Eres el Portfolio Advisor de Mission Control OS.
Tu misión: analizar el estado financiero y operativo del portafolio y recomendar prioridades.

REGLAS:
- Basa todas las recomendaciones en datos reales del portafolio.
- Prioriza proyectos por impacto en revenue total, no por popularidad.
- Cuando un proyecto tiene alto tráfico y $0 MRR, siempre señala la oportunidad.
- Responde en máximo 4 oraciones con datos específicos.`,
    tools: [
      { id: "read_metrics",  name: "read_metrics",   description: "Leer métricas de todos los proyectos",            category: "read", enabled: true  },
      { id: "query_revenue", name: "query_revenue",  description: "Consultar datos de revenue en Supabase",           category: "read", enabled: true  },
      { id: "call_llm",      name: "call_llm",       description: "Llamar a modelo para análisis de tendencias",      category: "ai",   enabled: true  },
    ],
    actions: [
      { id: "generate_report", name: "Generar reporte",      description: "Crea reporte semanal del portafolio en PDF/MD", requiresApproval: false, enabled: true  },
      { id: "flag_risk",       name: "Marcar riesgo",         description: "Etiqueta proyectos con indicadores de riesgo",  requiresApproval: false, enabled: true  },
    ],
    skills: [
      { id: "outcomes",       label: "outcomes",      description: "Ingerir datos de revenue y conversión", enabled: true  },
      { id: "cost-optimizer", label: "cost-optimizer", description: "Calcular unit economics del portafolio", enabled: true  },
    ],
    memory: {
      contextWindow: 50000,
      retainHistory: false,
      historyDepth: 5,
      crossProjectMemory: true,
      factoryBrainAccess: true,
    },
  },
  {
    agent: "compliance",
    label: "Compliance",
    model: "claude-sonnet-4-6",
    maxTokens: 2048,
    humanApprovalRequired: true,
    systemPrompt: `Eres el Compliance Agent de Mission Control OS.
Tu misión: asegurar que todos los proyectos cumplan con regulaciones legales antes de publicar.

REGLAS:
- LATAM first: prioriza LFPDPPP (México), LGPD (Brasil), SIC (Colombia).
- Cualquier app que recolecte datos personales DEBE tener aviso de privacidad.
- Genera el documento legal y la página, nunca solo el texto sin implementar.
- Si hay datos de menores involucrados, escala inmediatamente y detén el deploy.
- Revisa biometría, geolocalización, y datos sensibles como categorías especiales.`,
    tools: [
      { id: "read_code",      name: "read_code",       description: "Auditar el codebase buscando recolección de datos",   category: "read",  enabled: true  },
      { id: "read_db_schema", name: "read_db_schema",  description: "Leer esquema de Supabase para detectar datos PII",    category: "read",  enabled: true  },
      { id: "write_legal",    name: "write_legal",     description: "Generar documentos legales (privacidad, términos)",   category: "write", enabled: true  },
      { id: "open_pr",        name: "open_pr",         description: "Abrir PR con páginas de compliance",                  category: "write", enabled: true  },
    ],
    actions: [
      { id: "audit_privacy",  name: "Auditar privacidad",   description: "Escanea el proyecto buscando recolección de PII sin aviso", requiresApproval: false, enabled: true  },
      { id: "gen_privacy",    name: "Generar /privacidad",  description: "Crea página de aviso de privacidad LFPDPPP",               requiresApproval: true,  enabled: true  },
      { id: "gen_terms",      name: "Generar /terminos",    description: "Crea página de términos y condiciones",                    requiresApproval: true,  enabled: true  },
      { id: "add_cookie",     name: "Agregar banner cookies", description: "Implementa banner de consentimiento de cookies",         requiresApproval: true,  enabled: true  },
      { id: "block_deploy",   name: "Bloquear deploy",      description: "Detiene deploy si hay violación de compliance crítica",    requiresApproval: false, enabled: false, },
    ],
    skills: [
      { id: "compliance",  label: "compliance",  description: "Skill base de compliance con templates legales LATAM", enabled: true  },
      { id: "add-emails",  label: "add-emails",  description: "Configurar email de data deletion requests",          enabled: true  },
    ],
    memory: {
      contextWindow: 150000,
      retainHistory: true,
      historyDepth: 30,
      crossProjectMemory: true,
      factoryBrainAccess: false,
    },
  },
];

// ── Demo Chat Responses ──────────────────────────────────────────
// keyword → respuesta simulada por agente. El match es por substring simple.
export const DEMO_CHAT_RESPONSES: Record<AgentType, Array<{ keywords: string[]; response: string }>> = {
  general: [
    {
      keywords: ["hola", "hi", "hey", "inicio", "start"],
      response: "Hola. Soy el OS Agent. Tienes **8 proyectos** en portafolio con **$1,323/mes** en MRR total. Guardian reporta **2 alertas críticas** activas — Meridian Real Estate y RidePG. Factory Brain tiene **12 patrones** aprendidos, 8 PROVEN. ¿En qué te ayudo?",
    },
    {
      keywords: ["estado", "resumen", "status", "overview"],
      response: "Estado actual del portafolio: **5 proyectos healthy**, 1 degraded (Dental), 1 down (Meridian), 1 deploying (FractalOS). Revenue total **$1,323 MRR** con crecimiento promedio de +47% mes a mes. Guardian tiene auto-fix activo en 2 incidentes.",
    },
    {
      keywords: ["mejor", "top", "mayor", "más"],
      response: "El proyecto con mejor performance es **NuestraOferta**: $4,875/mes, 99.97% uptime, 4.1% conversión. Mejor crecimiento: **Pipe0.1** con +156% MRR mes a mes. Mejor confiabilidad: **Mission Control** con 0 errores en 24h.",
    },
    {
      keywords: ["problema", "error", "fallo", "caído", "down"],
      response: "Dos incidentes activos: **Meridian Real Estate** está down (412 errores, TypeError en /api/listings — Guardian abrió PR #35 para fix). **Dental Mgmt** degraded (P95 latencia en 1240ms por query sin índice — PR #18 abierto). Meridian es el más urgente.",
    },
    {
      keywords: [],
      response: "Entendido. Puedo ayudarte con análisis del portafolio, alertas de Guardian, patrones del Brain, o estrategias de adquisición. También puedes cambiar de agente con las pills de arriba para ir directo al especialista.",
    },
  ],
  portfolio: [
    {
      keywords: ["revenue", "ingreso", "mrr", "dinero", "factura"],
      response: "MRR total del portafolio: **$1,323/mes**. Top 3: NuestraOferta ($4,875), Pipe0.1 ($765), FractalOS ($490). Crecimiento promedio: **+47% MoM**. RidePG tiene el mayor potencial sin monetizar — 834 usuarios activos con $0 MRR actual.",
    },
    {
      keywords: ["conversión", "conversion", "signup", "registro"],
      response: "Mejor conversión: **Pipe0.1 con 6.8%** (freemium 14 días). Promedio del portafolio: 3.2%. Los proyectos con gradient-mesh promedian 4.0% vs 1.8% en otros design systems — dato confirmado por Factory Brain con 91% de confianza.",
    },
    {
      keywords: ["usuarios", "users", "activos", "tráfico"],
      response: "Total activos en portafolio: **3,257 usuarios**. Mayor base: NuestraOferta (1,247). Mayor crecimiento reciente: FractalOS (+12% semana). Proyectos sin usuarios reales: Mission Control (internal). Meridian perdió todos sus usuarios activos desde que cayó.",
    },
    {
      keywords: ["uptime", "disponibilidad", "reliability"],
      response: "Uptime promedio del portafolio: **97.1%**. Mejor: Mission Control y NuestraOferta (99.97-100%). Peor: Meridian Real Estate (81.2% — actualmente down). Dental Mgmt degraded con P95 en 1240ms. Guardian tiene auto-fix activo en ambos.",
    },
    {
      keywords: [],
      response: "El portafolio genera **$1,323 MRR** con 8 proyectos. 5 healthy, 1 degraded, 1 down, 1 deploying. Revenue concentrado en NuestraOferta (37% del total). Oportunidad: RidePG tiene 834 usuarios sin modelo de monetización activo.",
    },
  ],
  guardian: [
    {
      keywords: ["crítico", "critico", "crítica", "urgente", "down"],
      response: "**Alerta crítica activa**: Meridian Real Estate está down — TypeError en /api/listings, 412 errores en 2h. Guardian creó PR #35 con null-check fix. Requiere tu aprobación para merge. ¿Revisamos el PR?",
    },
    {
      keywords: ["fix", "arreglo", "pr", "pull request"],
      response: "Guardian tiene **2 PRs de auto-fix abiertos**: PR #35 en Meridian (null check en /api/listings, crítico) y PR #18 en Dental (índice en clinic_id, warning latencia). Ambos esperan aprobación humana antes de merge.",
    },
    {
      keywords: ["error", "errores", "fallo"],
      response: "Errores activos: **Meridian** 412 errores (TypeError, crítico), **Dental Mgmt** latencia degradada (1240ms P95, no errores directos), **NuestraOferta** 2 errores menores (no críticos). Total portafolio: 419 errores en 24h, 98.6% provienen de Meridian.",
    },
    {
      keywords: ["autofix", "auto-fix", "automático"],
      response: "Auto-fix activo en **5 de 8 proyectos**. Esta semana Guardian abrió 3 PRs, 1 ya mergeado automáticamente (RidePG — null guard en driver location). Los otros 2 esperan revisión. En 4 meses operando: **0 regresiones en main** con auto-fix habilitado.",
    },
    {
      keywords: [],
      response: "Guardian activo. **2 alertas críticas** sin resolver: Meridian Real Estate (down, PR abierto) y Dental Mgmt (degraded, PR de índice pendiente). Auto-fix branching en ambos. ¿Quieres detalles de algún incidente específico?",
    },
  ],
  brain: [
    {
      keywords: ["diseño", "design", "design system", "visual", "ui"],
      response: "El patrón con más evidencia en diseño: **gradient-mesh convierte 2x vs neumorphism** (91% confianza, 4 proyectos, PROVEN). NuestraOferta 4.1% vs Meridian 0% con neumorphism. En B2C LatAm, gradient-mesh es la apuesta segura.",
    },
    {
      keywords: ["stack", "tecnología", "tecnologia", "framework"],
      response: "Stack más probado: **Next.js + Supabase + Polar** en 6 proyectos sin incidentes de pagos. Polar como MoR: setup en <2h, 0 chargebacks. Supabase con RLS desde migración 0: 0 data leaks en 8 proyectos. next-intl desde día 1 ahorra 3 días de refactor.",
    },
    {
      keywords: ["onboarding", "activación", "activacion", "retención"],
      response: "Patrón probado: **onboarding en <3 pasos dobla activación** (84% confianza, PROVEN). RidePG: 31% → 67% activación. NuestraOferta: 28% → 54%. Clave: mostrar valor real en el paso 1, sin formularios largos ni tours opcionales.",
    },
    {
      keywords: ["costo", "ai", "ia", "modelo", "precio"],
      response: "Patrón de costo IA: **OpenRouter routing reduce costo 67%** (88% confianza, PROVEN). Haiku para clasificación + Sonnet solo para generación. FractalOS: $0.08 → $0.026/usuario. Pipe0.1: $0.11 → $0.033/usuario. Implementado con el skill cost-optimizer.",
    },
    {
      keywords: [],
      response: "Factory Brain tiene **12 patrones** con evidencia real. Los más accionables: gradient-mesh para conversión B2C, Polar para pagos LatAm sin fricción, onboarding <3 pasos para activación. ¿Qué dimensión quieres explorar — diseño, stack, adquisición, o pricing?",
    },
  ],
  acquisition: [
    {
      keywords: ["seo", "orgánico", "organico", "google", "búsqueda"],
      response: "Patrón probado: **SEO programático genera 400 páginas en 1 deploy** (72% confianza, LIKELY). NuestraOferta: 400 páginas /ciudad/categoria → 2,300 visitas orgánicas/mes en 45 días. Para tus proyectos sin tráfico, esta es la palanca más rápida sin CAC.",
    },
    {
      keywords: ["usuarios", "primeros", "tráfico", "trafico", "conseguir"],
      response: "Proyectos sin estrategia de adquisición documentada: **RidePG** (834 usuarios pero sin SEO), **BusinessOS** (237 usuarios). Para RidePG: genera páginas /transporte-[ciudad] en las 10 ciudades principales. Para BusinessOS: LinkedIn content + caso de uso real cada semana.",
    },
    {
      keywords: ["contenido", "redes", "social", "linkedin"],
      response: "Para B2B SaaS LatAm: **LinkedIn es el canal con mejor ROI sin presupuesto**. Comparte el problema que resuelves + resultado real de un cliente, 2 veces por semana. FractalOS consiguió sus primeros 50 usuarios en 3 semanas con este approach. Sin ads todavía.",
    },
    {
      keywords: ["ads", "pagado", "paid", "publicidad"],
      response: "Ads pagados recomendados cuando ya tienes **al menos 2% de conversión orgánica** y el CAC está validado. RidePG tiene 834 usuarios pero conversión 0% a pago — primero validar modelo de monetización antes de invertir en ads. Foco en orgánico mientras tanto.",
    },
    {
      keywords: [],
      response: "Del portafolio, **3 proyectos tienen tráfico orgánico sin estrategia** documentada: RidePG, BusinessOS, y Mission Control. La táctica más rápida: SEO programático con Next.js — 200 páginas /[ciudad]/[categoria] indexables en 2-3 semanas. ¿Empezamos por cuál?",
    },
  ],
};

export function matchDemoChatResponse(agentType: AgentType, userMessage: string): string {
  const responses = DEMO_CHAT_RESPONSES[agentType];
  const lower = userMessage.toLowerCase();

  for (const entry of responses) {
    if (entry.keywords.length > 0 && entry.keywords.some((k) => lower.includes(k))) {
      return entry.response;
    }
  }
  // Último item es el default (keywords vacío)
  return responses[responses.length - 1].response;
}

export const DEMO_GREETINGS: Record<AgentType, string> = {
  general: "Hola. Soy el **OS Agent** — tengo visibilidad de todo el portafolio. Hay **8 proyectos**, **2 alertas críticas** activas, y **12 patrones** en Factory Brain. ¿En qué te ayudo?",
  portfolio: "**Portfolio Advisor** listo. El portafolio genera **$1,323 MRR** con 3,257 usuarios activos. NuestraOferta lidera con $4,875/mes. ¿Quieres un análisis de revenue, conversión, o uptime?",
  guardian: "**Guardian Ops** activo. Monitoreo 8 proyectos en tiempo real. Alertas abiertas: Meridian Real Estate (crítico, down) y Dental Mgmt (warning, latencia). Auto-fix branching en ambos. ¿Revisamos?",
  brain: "**Factory Brain** conectado. Tengo **12 patrones** con evidencia de proyectos reales — 8 PROVEN, 4 LIKELY. Los patrones de diseño y stack tienen la mayor confianza. ¿Qué dimensión exploramos?",
  acquisition: "**Acquisition Agent** aquí. Tres proyectos en el portafolio sin estrategia de adquisición documentada. El canal más rápido sin CAC: SEO programático con Next.js. ¿Empezamos por qué proyecto?",
};
